name: mowl313
channels:
  - conda-forge
dependencies:
  - python=3.13
  - click
  - deprecated
  - gensim>=4.3.0
  - gradle
  - JPype1=1.5.1
  - pandas
  - pytorch
  - pyyaml
  - requests
  - scikit-learn
  - scipy<1.16.0  
  - tqdm
  - urllib3
  - pip
  - pip:
    - pykeen==1.11.0
    - temp
    - class-resolver==0.5.4
    
